# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb-primary
      - biling
      - rabbitmq
      - auth
      # - mongodb-secondary
      # - mongodb-arbiter
    volumes:
      - .:/usr/src/apps
      - /usr/src/apps/node_modules
    ports:
      - '3000:3000'

  biling:
    build:
      context: .
      dockerfile: ./apps/biling/Dockerfile
      target: development
    command: npm run start:dev biling
    env_file:
      - ./apps/biling/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
      - auth
      # - mongodb-secondary
      # - mongodb-arbiter
    volumes:
      - .:/usr/src/apps
      - /usr/src/apps/node_modules

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
    volumes:
      - .:/usr/src/apps
      - /usr/src/apps/node_modules

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  mongodb-primary:
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'
  # mongodb-secondary:
  #   image: docker.io/bitnami/mongodb:6.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

  # mongodb-arbiter:
  #   image: docker.io/bitnami/mongodb:6.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
  #     - MONGODB_REPLICA_SET_MODE=arbiter
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
